### ISSUE TITLE
Custom sensitive information types limitations

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/EMDocs#208]
Given the product rollout cadence between Commercial and GCC/GCCH/DoD national clouds, it may be worth mentioning a few additional AIP unified labeling "gotchas" - 

1.) As of writing, it is currently not possible to create custom sensitive information types in the Microsoft 365 Security & Compliance Center using the GUI [referenced here](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type?view=o365-worldwide), this is only available via the PowerShell methods [referenced here](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell?view=o365-worldwide). 

2.) As of writing, there are substantially more Microsoft published SITs in Commercial tenants (~152) than GCCH tenants (~100).

![image](https://user-images.githubusercontent.com/17114534/93137728-8fbf4300-f6a3-11ea-826e-8f690df21176.png)

**Comment by batamig** [comment]
Hi @milesgratz - thank you for opening this issue, and apologies for the late response - this was only brought to my attention today. 

There've been some updates since Sept 2020, and we've made changes to the [AIP service description article](https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-aip-premium-govt-service-description) as needed. 

In any case, we'll take a fresh look at the page with your feedback in mind to ensure that the content's correct.
I'm closing this for now, but feel free to add additional comments if you have any. 

#please-close
